---
title: sophie site
timezone: UTC
collections:
  cours:
    title: Cours
    output: true
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: products
  values:
    layout: product
    permalink: "/products/:title/"
    name: ''
    price: 0.0
    sku: ''
    image: ''
    weight: 0.0
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: poulet
baseline: pour les poulets
copyright: sophie
encodage: UTF-8
telephone: 00 00 00 00 00
mail: sophie.lucas@etu.univ-rouen.fr
adresse: 7 bis rue des poulet
permalink: pretty
