title: sophie site
description: poulet
baseline: pour les poulets
copyright: sophie
encodage: UTF-8
telephone: 00 00 00 00 00
mail: sophie.lucas@etu.univ-rouen.fr
adresse: 7 bis rue des poulet

collections:
  cours:
    output: true
